apps/pages/urls.py
from django.urls import path

from apps.pages.views import about_view, contact_page_view, home_view, not_found_view


app_name = 'pages'

urlpatterns = [
    path('', home_view, name='home'),
    path('contact/', contact_page_view, name='contact'),
    path('about/', about_view, name='about'),
    path('404/', not_found_view, name = '404'),
    # path('test/', test_contact, name='test')
]

core/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('apps.pages.urls'), name='pages'),
    path('blogs/', include('apps.blogs.urls'), name='blogs'),
    path('products/', include('apps.products.urls'), name='products'),
    path('accounts/', include('apps.accounts.urls'), name='accounts'),
    path('basket/',include('apps.basket.urls'),name='basket'),
    path('wishlist/', include('apps.wishlist.urls'), name='wishlist'),
    path('orders/', include('apps.orders.urls'), name='orders'),



)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/pages/about-us.html
{% extends 'layout/base.html' %}
{% load static %}
{% load i18n %}
{% load my_tags %}
{% block title %}{% trans 'About' %}{% endblock %}
{% block body_id %}about-us{% endblock %}
{% block body_class %}blog{% endblock %}
{% block content %}	
	<div class="main-content">
		<div id="wrapper-site">
			<div id="content-wrapper">
				
				<!-- breadcrumb -->
				<nav class="breadcrumb-bg">
					<div class="container no-index">
						<div class="breadcrumb">
							<ol>
								<li>
									<a href="#">
										<span>{% trans 'Home' %}</span>
									</a>
								</li>
								<li>
									<a href="#">
										<span>{% trans 'About us' %}</span>
									</a>
								</li>
							</ol>
						</div>
					</div>
				</nav>
				<div id="main">
					<div class="page-home">
						<div class="container">
							<div class="about-us-content">
								
								<h1 class="title-page">{% trans 'About Us' %}</h1>
								<div class="row">
									<div class="col-lg-6 col-md-6 col-sm-6 right">
										<a href="#">
											<img class="img-fluid" src="{% static 'img/other/1.jpg' %}" alt="#" />
										</a>
									</div>
									<div class="col-lg-6 col-md-6 col-sm-6 left">
										<div class="cms-block f-right">
											<h3 class="page-subheading">{% trans 'WHO WE ARE' %}</h3>
											<p>{% blocktrans %}We are a team of passionate creators dedicated to bringing your vision to life.
                                                With a foundation built on quality, innovation, and trust, our mission is to deliver exceptional
                                                solutions that not only meet your needs but also inspire new possibilities. We believe in the power
                                                of great ideas and the hard work it takes to turn them into reality.{% endblocktrans %}</p>
											<p>{% blocktrans %}Our team has a proven track record of success, with years of experience helping businesses
                                                and individuals achieve their goals. We are committed to building long-lasting relationships with our clients,
                                                ensuring that every project, big or small, receives our full attention and dedication. Your success is our
                                                ultimate measure of achievement.{% endblocktrans %}</p>
											<a>
												<img class="img-fluid" src="{% static 'img/other/4.png' %}" alt="#" />
												<span>{% trans 'Mr. kwang shang - CEO' %}</span>
											</a>
										</div>
									</div>
									<div class="col-lg-6 col-md-6 col-sm-6 right">
										<div class="cms-block f-left">
											<h3 class="page-subheading">{% trans 'WHAT WE DO' %}</h3>
											<p>{% blocktrans %}We specialize in delivering comprehensive and innovative solutions designed to meet your
                                                specific needs. From initial concept to final execution, our team provides a full range of
                                                services that drive results. Our expertise spans across multiple disciplines, allowing us to create
                                                high-quality, impactful products and experiences for our clients and their customers.{% endblocktrans %}</p>
											<p>{% blocktrans %}We work closely with you at every stage, offering transparency and communication to ensure your project is completed
                                                to the highest standards. Our commitment is to deliver not just a product, but a complete solution
                                                that empowers your business to thrive{% endblocktrans %}</p>
										</div>
									</div>
									<div class="col-lg-6 col-md-6 col-sm-6 left">
										<a href="#">
											<img class="img-fluid" src="{% static 'img/other/2.jpg' %}" alt="#" />
										</a>
									</div>
									<div class="col-lg-6 col-md-6 col-sm-6 right">
										<a href="#">
											<img class="img-fluid" src="{% static 'img/other/3.jpg' %}" alt="#" />
										</a>
									</div>
									<div class="col-lg-6 col-md-6 col-sm-6 left">
										<div class="cms-block f-right">
											<h3 class="page-subheading no-before">{% trans 'MEET OUR TEAM' %}</h3>
											<div class="testimonials owl-carousel owl-theme owl-loaded owl-drag">
												<div class="item">
													<div class="name">{% trans 'William James' %}</div>
													<div class="position">{% trans 'Designer - Stylish' %}</div>
													<p>{% blocktrans %}Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin, lorem
														quis biben dum auctor, nisi elit consequat ipsum, nec sagittis sem
														nibh id elit. Duis sed odio sit amet nibh vultate cursus a sit amet
														mauris. Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin,
														lorem quis bibendum auctor, nisi elit conse quat ipsum {% endblocktrans %}
													</p>
												</div>
												<div class="item">
													<div class="name">{% trans 'Seller Smith' %}</div>
													<div class="position">{% trans 'Web developer' %}</div>
													<p>{% blocktrans %}Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin, lorem
														quis biben dum auctor, nisi elit consequat ipsum, nec sagittis sem
														nibh id elit. Duis sed odio sit amet nibh vultate cursus a sit amet
														mauris. {% endblocktrans %}
													</p>
												</div>
												<div class="item">
													<div class="name">{% trans 'Peter Capidal' %}</div>
													<div class="position">{% trans 'Front-end Developer' %}</div>
													<p>{% blocktrans %} }Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin, lorem
														quis biben dum auctor, nisi elit consequat ipsum, nec sagittis sem
														nibh id elit. Duis sed odio sit amet nibh vultate cursus a sit amet
														mauris. Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin,
														lorem quis bibendum auctor, nisi elit conse quat ipsum {% endblocktrans %}
													</p>
												</div>
												<div class="item">
													<div class="name">{% trans 'David James' %}</div>
													<div class="position">{% trans 'Developer' %}</div>
													<p>{% blocktrans %}Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin, lorem
														quis biben dum auctor, nisi elit consequat ipsum, nec sagittis sem
														nibh id elit. Duis sed odio sit amet nibh vultate cursus a sit amet
														mauris.Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin,
														lorem quis bibendum auctor, nisi elit conse quat ipsum {% endblocktrans %}
													</p>
												</div>
											</div>
											<div class="social-content">
												<div class="social">
													<ul class="list-inline mb-0 justify-content-end">
														<li class="list-inline-item mb-0">
															<a href="#" target="_blank">
																<i class="fa fa-facebook"></i>
															</a>
														</li>
														<li class="list-inline-item mb-0">
															<a href="#" target="_blank">
																<i class="fa fa-twitter"></i>
															</a>
														</li>
														<li class="list-inline-item mb-0">
															<a href="#" target="_blank">
																<i class="fa fa-google"></i>
															</a>
														</li>
														<li class="list-inline-item mb-0">
															<a href="#" target="_blank">
																<i class="fa fa-instagram"></i>
															</a>
														</li>
													</ul>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

templates/pages/contact.html
{% extends 'layout/base.html' %}
{% load static %}
{% load i18n %}
{% load my_tags %}
{% block title %}{% trans 'Contact' %}{% endblock %}
{% block body_id %}contact{% endblock %}
{% block body_class %}blog{% endblock %}
{% block extra_css %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/errors.css' %}">
{% endblock %}
{% block content %} 
    <div class="main-content">
        <div id="wrapper-site">
            <div id="content-wrapper">

                <!-- breadcrumb -->
                <nav class="breadcrumb-bg">
                    <div class="container no-index">
                        <div class="breadcrumb">
                            <ol>
                                <li>
                                    <a href="#">
                                        <span>{% trans 'Home' %}</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <span>{% trans 'Contact' %}</span>
                                    </a>
                                </li>
                            </ol>
                        </div>
                    </div>
                </nav>
                <div id="main">
                    <div class="page-home">
                        <div class="container">
                            <h1 class="text-center title-page">{% trans 'Contact Us' %}</h1>
                            <div class="row-inhert">
                                <div class="header-contact">
                                    <div class="row">
                                        <div class="col-xs-12 col-sm-4 col-md-4">
                                            <div class="item d-flex">
                                                <div class="item-left">
                                                    <div class="icon">
                                                        <i class="zmdi zmdi-email"></i>
                                                    </div>
                                                </div>
                                                <div class="item-right d-flex">
                                                    <div class="title">{% trans 'Email:' %}</div>
                                                    <div class="contact-content">
                                                        <a href="mailto:support@domain.com">support@domain.com</a>
                                                        <br>
                                                        <a href="mailto:contact@domain.com">contact@domain.com</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-xs-12 col-sm-4 col-md-4">
                                            <div class="item d-flex">
                                                <div class="item-left">
                                                    <div class="icon">
                                                        <i class="zmdi zmdi-home"></i>
                                                    </div>
                                                </div>
                                                <div class="item-right d-flex">
                                                    <div class="title">{% trans 'Address:' %}</div>
                                                    <div class="contact-content">
                                                        {% trans '23 Suspendis matti, Visaosang Building District, NY Accums, North American' %}
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-xs-12 col-sm-4 col-md-4">
                                            <div class="item d-flex justify-content-end  last">
                                                <div class="item-left">
                                                    <div class="icon">
                                                        <i class="zmdi zmdi-phone"></i>
                                                    </div>
                                                </div>
                                                <div class="item-right d-flex">
                                                    <div class="title">{% trans 'Hotline:' %}</div>
                                                    <div class="contact-content">
                                                        0123-456-78910
                                                        <br>0987-654-32100
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="contact-map">
                                    <div id="map">
                                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3724.3785754726428!2d105.78134315594316!3d21.01753304734255!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x313454ab43c0c4db%3A0xdb6effebd6991106!2sKeangnam+Hanoi+Landmark+Tower!5e0!3m2!1svi!2s!4v1530175498947" allowfullscreen></iframe>
                                    </div>
                                </div>
                                <div class="input-contact">
                                    <p class="text-intro text-center">{% blocktrans %}"This modern furniture collection combines elegant design with
                                        functional comfort. Each piece is crafted from premium materials,
                                        ensuring both durability and style. Whether you are looking to furnish
                                        a new home or refresh an existing space, our catalog offers the perfect
                                        solution to elevate your living environment. We believe that great design
                                        should be accessible to everyone."{% endblocktrans %}
                                    </p>

                                    <p class="icon text-center">
                                        <a href="#">
                                            <img src="{% static 'img/other/contact' %}_mess.png" alt="img">
                                        </a>
                                    </p>

                                    <div class="d-flex justify-content-center">
                                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                                            <div class="contact-form">
                                                <form action="{% url 'pages:contact' %}" method="post" enctype="multipart/form-data">
                                                    {% csrf_token %}
                                                    {% if errors %}
                                                        <div class="alert alert-danger">
                                                            <h5>{% trans 'Warning' %}</h5>
                                                            {{ errors }}
                                                        </div>
                                                    {% endif %}
                                                    {% if messages %}
                                                      {% for message in messages %}
                                                        {% if message.tags == 'success' %}
                                                          <div class="alert-success2">
                                                            <div class="alert-icon">
                                                              <i class="bi bi-check-lg"></i>
                                                            </div>
                                                            <h4 style="color: green">{% trans 'Success!' %}</h4>
                                                            <p>{{ message }}</p>
                                                          </div>
                                                        {% endif %}
                                                      {% endfor %}
                                                    {% endif %}

                                                    <div class="form-fields">
                                                        <div class="form-group row">
                                                            <div class="col-md-6">
                                                                <input class="form-control" name="full_name" placeholder="{% trans 'Your name' %}">
                                                            </div>
                                                            <div class="col-md-6 margin-bottom-mobie">
                                                                <input class="form-control" name="email" type="email" value="" placeholder="{% trans 'Your email' %}">
                                                            </div>
                                                        </div>
                                                        <div class="form-group row">
                                                            <div class="col-md-12 margin-bottom-mobie">
                                                                <input class="form-control" name="subject" type="text" value="" placeholder="{% trans 'Subject' %}">
                                                            </div>
                                                        </div>
                                                        <div class="form-group row">
                                                            <div class="col-md-12">
                                                                <textarea class="form-control" name="message" placeholder="{% trans 'Message' %}" rows="8"></textarea>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div>
                                                        <button class="btn" type="submit" name="submitMessage">
                                                            <img class="img-fl" src="{% static 'img/other/contact' %}_email.png" alt="img">{% trans 'Send message' %}
                                                        </button>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/pages/test-contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {{ form }}
    <h1>Test_contact</h1>
</body>
</html>