apps/blogs/urls.py
from django.urls import path
from apps.blogs.views import BlogDetailView, BlogListView, BlogFilterView, BlogSearchView

app_name = 'blogs'

urlpatterns = [
    path('', BlogListView.as_view(), name='blogs_home'),
    path("search/", BlogSearchView.as_view(), name="search"),
    path("<int:pk>/", BlogDetailView.as_view(), name="detail"),
    path("filter/<str:filter_type>/<int:pk>/", BlogFilterView.as_view(), name="blog_filter"),
]

core/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('apps.pages.urls'), name='pages'),
    path('blogs/', include('apps.blogs.urls'), name='blogs'),
    path('products/', include('apps.products.urls'), name='products'),
    path('accounts/', include('apps.accounts.urls'), name='accounts'),
    path('basket/',include('apps.basket.urls'),name='basket'),
    path('wishlist/', include('apps.wishlist.urls'), name='wishlist'),
    path('orders/', include('apps.orders.urls'), name='orders'),



)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/blogs/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from apps.pages.models import BaseModel

class BlogCategoryModel(BaseModel):
    title = models.CharField(max_length=255)
    
    parent = models.ForeignKey(
        'self',
        on_delete=models.CASCADE,
        related_name='children',
        blank=True,
        null=True
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Blog category'
        verbose_name_plural = 'Blog categories'


class BlogTagModel(BaseModel):
    title = models.CharField(max_length=255)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Blog tag'
        verbose_name_plural = 'Blog tags'


class BlogAuthorModel(BaseModel):
    full_name = models.CharField(max_length=128)
    avatar = models.ImageField(
        upload_to='blog-author/'
    )
    bio = models.CharField(max_length=255)

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = 'Blog author'
        verbose_name_plural = 'Blog authors'


class BlogModel(BaseModel):
    class BlogStatus(models.TextChoices):
        DRAFT = 'DRAFT'
        PUBLISHED = 'PUBLISHED'
        DELETED = 'DELETED'

    image = models.ImageField(upload_to='blog-post/')
    title = models.CharField(max_length=255)
    content = RichTextUploadingField()
    status = models.CharField(
        max_length=20,
        choices=BlogStatus,
        default=BlogStatus.DRAFT
    )

    author = models.ForeignKey(
        BlogAuthorModel,
        on_delete=models.CASCADE,
        related_name='blogs',
    )
    category = models.ManyToManyField(
        BlogCategoryModel,
        related_name='blogs'
    )
    tag = models.ManyToManyField(
        BlogTagModel,
        related_name='blogs'
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Blog'
        verbose_name_plural = 'Blogs'


class BlogViewModel(BaseModel):
    user_ip = models.CharField(max_length=15)
    blog = models.ForeignKey(
        BlogModel, on_delete=models.CASCADE, related_name='views'
    )

    def __str__(self):
        return f"{self.user_ip} - {self.blog.id}"

    class Meta:
        verbose_name = 'Blog view'
        verbose_name_plural = 'Blog views'


from django.db import models


class BlogCommentModel(BaseModel):
    blog = models.ForeignKey(
        BlogModel,
        on_delete=models.CASCADE,
        related_name='comments',
        null=True,
        blank=True
    )
    name = models.CharField(max_length=100)
    email = models.EmailField()
    website = models.URLField(blank=True, null=True)
    message = models.TextField()

    class Meta:
        verbose_name = 'Contact Message'
        verbose_name_plural = 'Contact Messages'

    def __str__(self):
        return f"{self.name} - {self.email}"

apps/blogs/forms.py
from django import forms
from .models import BlogCommentModel

class ContactForm(forms.ModelForm):
    class Meta:
        model = BlogCommentModel
        fields = ['name', 'email', 'website', 'message']

apps/blogs/views.py
from django.views.generic import ListView, DetailView
from django.shortcuts import redirect
from django.http import Http404
from django.contrib import messages
from django.db.models import Q

from apps.blogs.models import BlogModel, BlogCategoryModel, BlogTagModel, BlogCommentModel


# --- BLOG SEARCH VIEW ---
class BlogSearchView(ListView):
    model = BlogModel
    template_name = "blogs/blog-list-sidebar-left.html"
    context_object_name = "blogs"

    def get_queryset(self):
        query = self.request.GET.get('s', '').strip()

        if query:
            words = query.split()
            q_objects = Q()
            for word in words:
                q_objects |= (
                        Q(title__icontains=word) |
                        Q(content__icontains=word) |
                        Q(category__title__icontains=word) |
                        Q(tag__title__icontains=word)  # singular tag
                )
            queryset = BlogModel.objects.filter(
                q_objects,
                status=BlogModel.BlogStatus.PUBLISHED
            ).distinct()
        else:
            queryset = BlogModel.objects.filter(status=BlogModel.BlogStatus.PUBLISHED)

        self.search_query = query
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["search_query"] = getattr(self, "search_query", "")
        # Sidebar ma’lumotlari
        context["parent_categories"] = BlogCategoryModel.objects.filter(parent__isnull=True)
        context["tags"] = BlogTagModel.objects.all()
        context["recent_blogs"] = BlogModel.objects.filter(
            status=BlogModel.BlogStatus.PUBLISHED
        ).order_by('-created_at')[:5]
        # Header search uchun
        context["search_type"] = "blogs"
        return context


# --- BLOG LIST VIEW ---
class BlogListView(ListView):
    template_name = 'blogs/blog-list-sidebar-left.html'
    context_object_name = "blogs"
    paginate_by = 3

    def get_queryset(self):
        return BlogModel.objects.filter(status=BlogModel.BlogStatus.PUBLISHED)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["parent_categories"] = BlogCategoryModel.objects.filter(parent__isnull=True)
        context["tags"] = BlogTagModel.objects.all()
        context["recent_blogs"] = BlogModel.objects.filter(
            status=BlogModel.BlogStatus.PUBLISHED
        ).order_by('-created_at')[:2]
        context["search_type"] = "blogs"
        return context


# --- BLOG DETAIL VIEW ---
class BlogDetailView(DetailView):
    model = BlogModel
    template_name = "blogs/blog-detail.html"
    pk_url_kwarg = "pk"
    context_object_name = "blog"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        blog = self.get_object()

        category = blog.category.first()
        parent_category = category.parent if category else None

        related_blogs = BlogModel.objects.filter(
            category__in=blog.category.all()
        ).exclude(id=blog.id).distinct()[:3]

        comments = BlogCommentModel.objects.filter(blog=blog).order_by('-created_at')

        context["category"] = category
        context["parent_category"] = parent_category
        context["related_blogs"] = related_blogs
        context["comments"] = comments


        context["parent_categories"] = BlogCategoryModel.objects.filter(parent__isnull=True)
        context["tags"] = BlogTagModel.objects.all()
        context["recent_blogs"] = BlogModel.objects.filter(
            status=BlogModel.BlogStatus.PUBLISHED
        ).order_by('-created_at')[:3]


        context["search_type"] = "blogs"

        return context

    def post(self, request, *args, **kwargs):
        blog = self.get_object()
        name = request.POST.get('name')
        email = request.POST.get('email')
        website = request.POST.get('website')
        message = request.POST.get('message')

        if name and email and message:
            BlogCommentModel.objects.create(
                blog=blog,
                name=name,
                email=email,
                website=website,
                message=message
            )
            messages.success(request, 'Your comment has been submitted successfully!')
        else:
            messages.error(request, 'Please fill all required fields!')

        return redirect('blogs:detail', pk=blog.pk)


# --- BLOG FILTER VIEW ---
class BlogFilterView(ListView):
    template_name = 'blogs/blog-list-sidebar-left.html'
    context_object_name = "blogs"

    def get_queryset(self):
        filter_type = self.kwargs.get("filter_type")
        pk = self.kwargs.get("pk")
        blogs = BlogModel.objects.filter(status=BlogModel.BlogStatus.PUBLISHED)

        if filter_type == "category":
            try:
                category = BlogCategoryModel.objects.get(id=pk)
                blogs = blogs.filter(category=category)
                self.filter_title = category.title
            except BlogCategoryModel.DoesNotExist:
                raise Http404("Category not found")
        elif filter_type == "tag":
            try:
                tag = BlogTagModel.objects.get(id=pk)
                blogs = blogs.filter(tag=tag)
                self.filter_title = tag.title
            except BlogTagModel.DoesNotExist:
                raise Http404("Tag not found")
        else:
            raise Http404("Invalid filter type")

        return blogs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["filter_title"] = getattr(self, "filter_title", "")
        context["filter_type"] = self.kwargs.get("filter_type")

        context["parent_categories"] = BlogCategoryModel.objects.filter(parent__isnull=True)
        context["tags"] = BlogTagModel.objects.all()
        context["recent_blogs"] = BlogModel.objects.filter(
            status=BlogModel.BlogStatus.PUBLISHED
        ).order_by('-created_at')[:5]

        # Header search uchun
        context["search_type"] = "blogs"

        return context

templates/blogs/blog-list-sidebar-left.html
{% extends 'layout/base.html'%}
{% load static %}
{% load i18n %}
{% load my_tags %}
{% block title %} Blog-list {% endblock %}
{% block body_id %}blog-list-sidebar-left{% endblock %}
{% block body_class %}blog{% endblock %}
{% block content %}
<div class="main-content">
        <div id="wrapper-site">
            <div id="content-wrapper">
                <div id="main">
                    <div class="page-home">

                        <!-- breadcrumb -->
                        <nav class="breadcrumb-bg">
                            <div class="container no-index">
                                <div class="breadcrumb">
                                    <ol>
                                        <li>
                                            <a href="{% url 'blogs:blogs_home'%}">
                                                <span>{% trans 'Home' %}</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                <span>{% trans 'Blogs' %}</span>
                                            </a>
                                        </li>
                                    </ol>
                                </div>
                            </div>
                        </nav>
                        <div class="container">
                            <div class="content">
                                <div class="row">
                                    <div class="sidebar-3 sidebar-collection col-lg-3 col-md-3 col-sm-4">

                                        {% include 'blogs/blog-sidebar.html' %}

                                    </div>
                                    <div class="col-sm-8 col-lg-9 col-md-9 flex-xs-first main-blogs">
                                        <h2>Recent Posts</h2>
                                    {% if blogs %}
                                        {% for blog in blogs %}
                                            <div class="list-content row">
                                                <div class="hover-after col-md-5 col-xs-12">
                                                    <a href="{% url 'blogs:detail' pk=blog.id %}">
                                                        <img src="{{ blog.image.url }}" alt="img">
                                                    </a>
                                                </div>
                                                <div class="late-item col-md-7 col-xs-12" >
                                                    <p class="content-title">
                                                        <a href="{% url 'blogs:detail' pk=blog.id %}"> {{ blog.title|slice:":40" }} </a>
                                                    </p>
                                                    <p class="post-info">
                                                        <span>{{ blog.created_at|date:"M d, Y" }}</span>
                                                        <span>113 Comments</span>
                                                        <span> {{ blog.author.full_name }} </span>
                                                    </p>
                                                    <p class="description">{{ blog.content|striptags|slice:":200" }}...
                                                    </p>
                                                    <span class="view-more">
                                                        <a href="{% url 'blogs:detail' pk=blog.id %}">view more</a>
                                                    </span>
                                                </div>
                                            </div>
                                        {% endfor %}
                                    {% else %}
                                        {% if filter_type == "category" %}
                                            <p>No blogs found in this category.</p>
                                        {% elif filter_type == "tag" %}
                                            <p>No blogs found for this tag.</p>
                                        {% else %}
                                            <p>No blogs found.</p>
                                        {% endif %}
                                    {% endif %}
                                        <div class="page-list col">
                                            <ul class="justify-content-center d-flex">
                                                {% if page_obj.has_previous %}
                                                    <li>
                                                        <a rel="prev" href="?page={{ page_obj.previous_page_number }}{% if search_query %}&s={{ search_query }}{% endif %}" class="previous js-search-link">
                                                            Previous
                                                        </a>
                                                    </li>
                                                {% else %}
                                                    <li>
                                                        <span class="previous disabled">Previous</span>
                                                    </li>
                                                {% endif %}

                                                {% for num in page_obj.paginator.page_range %}
                                                    {% if page_obj.number == num %}
                                                        <li class="current active">
                                                            <a rel="nofollow" href="#" class="disabled js-search-link">
                                                                {{ num }}
                                                            </a>
                                                        </li>
                                                    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                                                        <li>
                                                            <a rel="nofollow" href="?page={{ num }}{% if search_query %}&s={{ search_query }}{% endif %}" class="js-search-link">
                                                                {{ num }}
                                                            </a>
                                                        </li>
                                                    {% endif %}
                                                {% endfor %}

                                                {% if page_obj.has_next %}
                                                    <li>
                                                        <a rel="next" href="?page={{ page_obj.next_page_number }}{% if search_query %}&s={{ search_query }}{% endif %}" class="next js-search-link">
                                                            Next
                                                        </a>
                                                    </li>
                                                {% else %}
                                                    <li>
                                                        <span class="next disabled">Next</span>
                                                    </li>
                                                {% endif %}
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/blogs/blog-sidebar.html
{% load static %}
{% load i18n %}

<!-- category -->
<div class="sidebar-block">
    <div class="title-block">Categories</div>
    <div class="block-content">
        {% for parent in parent_categories %}
            <div class="cateTitle hasSubCategory open level1">
                <span class="arrow collapse-icons collapsed"
                    data-toggle="collapse"
                    data-target="#category{{ parent.id }}"
                    aria-expanded="false" role="status">
                    <i class="zmdi zmdi-minus"></i>
                    <i class="zmdi zmdi-plus"></i>
                </span>
                <a class="cateItem" href="{% url 'blogs:blog_filter' 'category' parent.id %}">{{ parent.title }}</a>

                <div class="subCategory collapse"
                    id="category{{ parent.id }}"
                    aria-expanded="true" role="status">
                    {% for child in parent.children.all %}
                        <div class="cateTitle">
                            <a href="{% url 'blogs:blog_filter' 'category' child.id %}" class="cateItem">{{ child.title }}</a>
                        </div>
                    {% empty %}
                        <div class="cateTitle">
                            <span class="text-muted">{% trans 'No subcategories' %}</span>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
    </div>
</div>

<!-- recent posts -->
<div class="sidebar-block">
    <div class="title-block">{% trans 'Recent Posts' %}</div>
    <div class="post-item-content">
        {% for blog in recent_blogs %}
        <div>
            <div class="late-item {% if forloop.first %}first-child{% endif %}">
                <a href="{% url 'blogs:detail' blog.id %}">
                    {% if blog.image %}
                        <img src="{{ blog.image.url }}" alt="{{ blog.title }}" class="img-fluid mb-2">
                    {% endif %}
                    <p class="content-title">{{ blog.title|upper }}</p>
                </a>
                <span>
                    <i class="zmdi zmdi-comments"></i>{{ blog.comments.count }} comment{{ blog.comments.count|pluralize }}
                </span>
                <span>
                    <i class="zmdi zmdi-calendar-note"></i>{{ blog.created_at|date:"d F Y" }}
                </span>
                <p class="description">{{ blog.content|striptags|truncatewords:15 }}</p>
                <p class="remove">
                    <a href="{% url 'blogs:detail' blog.id %}">{% trans 'READ MORE' %}</a>
                </p>
            </div>
        </div>
        {% empty %}
        <p style="text-align:center;color:#999;padding:20px;">{% trans 'No recent posts found.' %}</p>
        {% endfor %}
    </div>
</div>

<!-- product tag -->
<div class="sidebar-block product-tags">
    <div class="title-block">
        Blog Tags
    </div>

    <div class="block-content">
        <ul class="listSidebarBlog list-unstyled">
            {% for tag in tags %}
            <li>
                <a href="{% url 'blogs:blog_filter' 'tag' tag.id %}" title="Show blogs matching tag {{ tag.title }}">{{ tag.title }}</a>
            </li>
            {% empty %}
            <li><span class="text-muted">{% trans 'No tags available' %}</span></li>
            {% endfor %}
        </ul>
    </div>
</div>