apps/pages/urls.py
from django.urls import path

from apps.pages.views import about_view, contact_page_view, home_view, not_found_view


app_name = 'pages'

urlpatterns = [
    path('', home_view, name='home'),
    path('contact/', contact_page_view, name='contact'),
    path('about/', about_view, name='about'),
    path('404/', not_found_view, name = '404'),
    # path('test/', test_contact, name='test')
]

core/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('apps.pages.urls'), name='pages'),
    path('blogs/', include('apps.blogs.urls'), name='blogs'),
    path('products/', include('apps.products.urls'), name='products'),
    path('accounts/', include('apps.accounts.urls'), name='accounts'),
    path('basket/',include('apps.basket.urls'),name='basket'),
    path('wishlist/', include('apps.wishlist.urls'), name='wishlist'),
    path('orders/', include('apps.orders.urls'), name='orders'),



)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/layout/base.html
<!DOCTYPE html>
{% load static %}
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]><html class="ie ie9" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
<!--<![endif]-->
<html lang="en">


<!-- contact11:09-->
<head>
    <!-- Basic Page Needs -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %}</title>

    <meta name="keywords" content="Furniture, Decor, Interior">
    <meta name="description" content="Furnitica - Minimalist Furniture HTML Template">
    <meta name="author" content="tivatheme">


    <!-- Mobile Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,500,600,700" rel="stylesheet">

    <!-- Vendor CSS -->
    <link rel="stylesheet" href="{% static 'libs/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'libs/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'libs/nivo-slider/css/nivo-slider.css' %}">
    <link rel="stylesheet" href="{% static 'libs/nivo-slider/css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'libs/nivo-slider/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'libs/font-material/css/material-design-iconic-font.min.css' %}">
    <link rel="stylesheet" href="{% static 'libs/slider-range/css/jslider.css' %}">
    <link rel="stylesheet" href="{% static 'libs/owl-carousel/assets/owl.carousel.min.css' %}">

    <!-- Template CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/reponsive.css' %}">
    {% block extra_css %}{% endblock %}
</head>

<body id="{% block body_id %}{% endblock %}" class="{% block body_class %}{% endblock %}">
    {% url 'pages:home' as home_url %}
    {% if request.path == home_url %}
        {% include 'layout/header-home.html' %}
    {% else %}
        {% include 'layout/header-base.html' %}
    {% endif %}

    {% block content %}{% endblock %}

    {% if request.path == home_url %}
        {% include 'layout/footer-home.html' %}
    {% else %}
        {% include 'layout/footer-base.html' %}
    {% endif %}

    <!-- back top top -->
    <div class="back-to-top">
        <a href="#">
            <i class="fa fa-long-arrow-up"></i>
        </a>
    </div>

    {% include 'layout/mobile-menu.html' %}

    <!-- Page Loader -->
    <div id="page-preloader">
        <div class="page-loading">
            <div class="dot"></div>
            <div class="dot"></div>
            <div class="dot"></div>
            <div class="dot"></div>
            <div class="dot"></div>
        </div>
    </div>

    <!-- Vendor JS -->
    <script src="{% static 'libs/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'libs/popper/popper.min.js' %}"></script>
    <script src="{% static 'libs/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'libs/nivo-slider/js/jquery.nivo.slider.js' %}"></script>
    <script src="{% static 'libs/owl-carousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'libs/slider-range/js/tmpl.js' %}"></script>
    <script src="{% static 'libs/slider-range/js/jquery.dependClass-0.1.js' %}"></script>
    <script src="{% static 'libs/slider-range/js/draggable-0.1.js' %}"></script>
    <script src="{% static 'libs/slider-range/js/jquery.slider.js' %}"></script>

    <!-- Template JS -->
    <script src="{% static 'js/theme.js' %}"></script>
    {% block extra_js %}{% endblock %}
</body>


<!-- contact11:10-->
</html>

templates/layout/footer-base.html
{% load static %}
{% load i18n %}
{% load my_tags %}
<footer class="footer-one">
        <div class="inner-footer">
            <div class="container">
                <div class="footer-top col-lg-12 col-xs-12">
                    <div class=" row">
                        <div class="nov-html col-lg-4 col-sm-12 col-xs-12">
                            <div class="block">
                                <div class="block-content">
                                    <p class="logo-footer">
                                        <img src="{% static 'img/home/logo.png' %}" alt="img">
                                    </p>
                                    <p class="content-logo">{% blocktrans %}In the web design industry, modern furniture is highly significant.
                                        It's not just beautiful but also comfortable and functional. Choosing furniture for homes or offices
                                        requires a mix of elegance and practicality. Variety and quality play a crucial role in giving customers a great experience.
                                    {% endblocktrans %}
                                    </p>
                                </div>
                            </div>
                            <div class="block">
                                <div class="block-content">
                                    <ul>
                                        <li>
                                            <a href="#">{% trans 'About Us' %}</a>
                                        </li>
                                        <li>
                                            <a href="#">{% trans 'Reasons to shop' %}</a>
                                        </li>
                                        <li>
                                            <a href="#">{% trans 'What our customers say' %}</a>
                                        </li>
                                        <li>
                                            <a href="#">{% trans 'Meet the team' %}</a>
                                        </li>
                                        <li>
                                            <a href="#">{% trans 'Contact our buyers' %}</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="block">
                                <div class="block-content">
                                    <p class="img-payment ">
                                        <img class="img-fluid" src="{% static 'img/home/payment-footer.png' %}" alt="img">
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="nov-html col-lg-4 col-sm-6">
                            <div class="block m-top">
                                <div class="title-block">
                                    {% trans 'Contact Us' %}
                                </div>
                                <div class="block-content">
                                    <div class="contact-us">
                                        <div class="title-content">
                                            <i class="fa fa-home" aria-hidden="true"></i>
                                            <span>{% trans 'Address :' %}</span>
                                        </div>
                                        <div class="content-contact address-contact">
                                            <p>{% trans '123 Suspendis matti, Visaosang Building VST District NY Accums, North American' %}
                                            </p>
                                        </div>
                                    </div>
                                    <div class="contact-us">
                                        <div class="title-content">
                                            <i class="fa fa-envelope" aria-hidden="true"></i>
                                            <span>{% trans 'Email :' %}</span>
                                        </div>
                                        <div class="content-contact mail-contact">
                                            <p>support@domain.com</p>
                                        </div>
                                    </div>
                                    <div class="contact-us">
                                        <div class="title-content">
                                            <i class="fa fa-phone" aria-hidden="true"></i>
                                            <span>{% trans 'Hotline :' %}</span>
                                        </div>
                                        <div class="content-contact phone-contact">
                                            <p>+0012-345-67890</p>
                                        </div>
                                    </div>
                                    <div class="contact-us">
                                        <div class="title-content">
                                            <i class="fa fa-clock-o" aria-hidden="true"></i>
                                            <span>{% trans 'Opening Hours :' %}</span>
                                        </div>
                                        <div class="content-contact hours-contact">
                                            <p>{% trans 'Monday - Sunday / 08.00AM- 19.00' %}</p>
                                            <span>{% trans '(Except Holidays)' %}</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="tiva-modules col-lg-4 col-md-6">
                            <div class="block m-top">
                                <div class="block-content">
                                    <div class="title-block">{% trans 'Newsletter' %}</div>
                                    <div class="sub-title">{% trans 'Sign up to our newsletter to get the latest articles, lookbooks voucher codes direct to your inbox' %}
                                    </div>
                                    <div class="block-newsletter">
                                        <form action="#" method="post">
                                            <div class="input-group">
                                                <input type="text" class="form-control" name="email" value="" placeholder="{% trans 'Enter Your Email' %}">
                                                <span class="input-group-btn">
                                                    <button class="effect-btn btn btn-secondary " name="submitNewsletter" type="submit">
                                                        <span>{% trans 'subscribe' %}</span>
                                                    </button>
                                                </span>
                                            </div>
                                            <input type="hidden" name="action" value="0">
                                        </form>
                                    </div>
                                </div>
                            </div>
                            <div class="block m-top1">
                                <div class="block-content">
                                    <div class="social-content">
                                        <div class="title-block">
                                            {% trans 'Follow us on' %}
                                        </div>
                                        <div id="social-block">
                                            <div class="social">
                                                <ul class="list-inline mb-0 justify-content-end">
                                                    <li class="list-inline-item mb-0">
                                                        <a href="#" target="_blank">
                                                            <i class="fa fa-facebook"></i>
                                                        </a>
                                                    </li>
                                                    <li class="list-inline-item mb-0">
                                                        <a href="#" target="_blank">
                                                            <i class="fa fa-twitter"></i>
                                                        </a>
                                                    </li>
                                                    <li class="list-inline-item mb-0">
                                                        <a href="#" target="_blank">
                                                            <i class="fa fa-google"></i>
                                                        </a>
                                                    </li>
                                                    <li class="list-inline-item mb-0">
                                                        <a href="#" target="_blank">
                                                            <i class="fa fa-instagram"></i>
                                                        </a>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="block m-top1">
                                <div class="block-content">
                                    <div class="payment-content">
                                        <div class="title-block">
                                            {% trans 'Payment accept' %}
                                        </div>
                                        <div class="payment-image">
                                            <img class="img-fluid" src="{% static 'img/home/payment.png' %}" alt="img">
                                        </div>
                                    </div>
                                    <!-- Popup newsletter -->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="tiva-copyright">
            <div class="container">
                <div class="row">
                    <div class="text-center col-lg-12 ">
                        <span>
                            <a target="_blank" href="https://www.templateshub.net">{% trans 'Templates Hub' %}</a>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </footer>